name: Self-hosted runner; (release)

on:
  push:
    tags:
      - v*

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  DIST_TMP_DIR: /home/dev/dist/bisheng_rt_${{ github.run_id }}

jobs:
  setup:
    name: Setup
    runs-on: [self-hosted, cpu]
    steps:
      - run: |
          if [[ -d ${{ env.DIST_TMP_DIR }} ]]; then
            rm -fr ${{ env.DIST_TMP_DIR }}/*
          else
            mkdir -p ${{ env.DIST_TMP_DIR }}
          fi

  upload:
    runs-on: [self-hosted, cpu]
    steps:
      - name: Launcher docker
        uses: actions/checkout@v2

      # Dowload pre-compiled bins, compiled in internal
      - name: Download bisheng-rt bins
        id: download_bisheng_rt_bins
        run: |
          cd ./docker/prod/
          RT_VER=$(cat components_version.txt |grep rt= | awk -F'=' '{print $2}')
          RT_ENT_VER=$(cat components_version.txt |grep rt_enterprise= | awk -F'=' '{print $2}')
          PYBACKEND_LIBS_VER=$(cat components_version.txt |grep bisheng_pybackend_libs= | awk -F'=' '{print $2}')
          echo "PYBACKEND_LIBS_VER=${PYBACKEND_LIBS_VER}" >> $GITHUB_ENV
          wget -q --no-check-certificate ${{ secrets.FILE_NEXUS_REPO }}/bisheng-rt-${RT_VER}.tar.gz 
          tar zxf bisheng-rt-${RT_VER}.tar.gz
          rm bisheng-rt-${RT_VER}.tar.gz
          wget -q  --no-check-certificate ${{ secrets.FILE_NEXUS_REPO }}/bisheng-rt-enterprise-${RT_ENT_VER}.tar.gz
          tar zxf bisheng-rt-enterprise-${RT_ENT_VER}.tar.gz
          rm bisheng-rt-enterprise-${RT_ENT_VER}.tar.gz

      # Build bisheng-rt and push Docker hub
      - name: Build bisheng-rt and push
        id: docker_build_backend
        run: |
          tag=${{ github.ref_name }}
          ver=${tag:1}
          docker build -t dataelement/bisheng-rt:${ver} -f Dockerfile .
          docker push dataelement/bisheng-rt:${ver}
